platform :ios, '9.0'

target 'FMAliyunOSSKitExample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

pod 'FMAliyunOSSKit', :path => './../'

end
